[tool.pytest.ini_options]
addopts = "--verbose --cov pyhrv --cov-report term-missing"
norecursedirs= ".* *.egg* build dist conda.recipe"
testpaths = [
    "tests",
]

[tool.isort]
# Setup for compatibility with black
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
length_sort = true
skip = [".tox",".venv","build","dist"]
known_standard_library = ["setuptools","pkg_resources"]
known_test = "pytest"
known_first_party = "pyhrv"
sections = ["FUTURE","STDLIB","COMPAT","TEST","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
default_section = "THIRDPARTY"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.dvc
    | \.ci
    | \.run
    | \.mypy_cache
    | \.pytest_cache
    | \.ipynb_checkpoints
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | data
    | out
  )/
  | __foo__.py           # also separately exclude a specific file (example)
)
'''
